<h2>accordion: 手风琴面板</h2>
<div id="accordion" data-mage-init='{ "accordion": {} }'>
    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Title 1</span>
        </div>
    </div>
    <div data-role="content">Content 1</div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Title 2</span>
        </div>
    </div>
    <div data-role="content">Content 2</div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Title 3</span>
        </div>
    </div>
    <div data-role="content">Content 3</div>
</div>

<!-- 声明方式 1 : data-mage-init='{ "accordion": {} }' -->
<!-- 声明方式 2  -->
<script>
    require([
        'jquery',
        'accordion'], function ($) {
        $("#accordion").accordion();
    });
</script>
<!-- 声明方式 3  -->
<!-- <script type="text/x-magento-init">
{
    "#accordion": {
        "accordion": {}
    }
}
</script> -->




<hr>

<h2>datepicker: 日期选择器</h2>
<div><input type="text" readonly id="calendar"></div>
<script>
require([
    'jquery',
    'mage/calendar'
], function ( $ ) {
    // http://api.jqueryui.com/datepicker/
    // $.extend(true, $, {
    //     calendarConfig: {
    //         dateFormat: "yy-mm-dd"
    //     }
    // });
    $("#calendar").datepicker({
        dateFormat: "yy-mm-dd"
    });
});
</script>



<hr>



<h2>collapsible: </h2>

<div id="collapsible">
    <div data-role="title">
        <div data-role="trigger">
            <span>Title 1</span>
        </div>
    </div>
    <div data-role="content">Content 1</div>

</div>
<script>
require([
    'jquery',
    'mage/collapsible'
], function ( $ ) {
    //https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_collapsible.html
    $('#collapsible').collapsible({
        icons: {
            header: 'plus',
            activeHeader: 'minus'
        },
        animate: {
            duration:1000,
            easing:"easeOutCubic"
        }
    });
});
</script>





<hr>



<h2>DropdownDialog: 下拉对话框</h2>
<div><button id="handlerdialog">Dialog</button></div>

<div id="dialog" title="Basic dialog">
  <p>This is the default dialog which is useful for displaying information. The dialog window can be moved, resized and closed with the 'x' icon.</p>
</div>

<script>
//https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_dialog.html
require([
    'jquery',
    'mage/dropdown'
], function($){
    $("#dialog").dropdownDialog({
        triggerTarget: '#handlerdialog',
        closeOnMouseLeave: false,
        closeOnClickOutside: false
    });
})

</script>


<hr>

<h2>gallery</h2>
<div>
    <a href="https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_gallery.html">https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_gallery.html</a>
</div>


<hr>

<h2>List</h2>

<div id="list">
    <div data-role="item"><%= data._index_ %>&nbsp;&nbsp;<span data-button="remove">(-)</span></div>
    <div data-role="container"></div>
    <button data-button="add">(+)</button>
</div>


<script>
require(['jquery', 'mage/list'], function($) {
    $('#list').list({
        templateWrapper: '<fieldset></fieldset>'
    });
})
</script>


<hr>

<h2>Magnifier: 放大镜</h2>
<a href="https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_gallery_mg.html">https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_gallery_mg.html</a>

<hr>


<h2>Loader</h2>
<pre>显示loading-mask, 不添加任何class</pre>
<div><button id="showloader">show loader</button><button id="hideloader">hide loader</button></div>
<script>
require(['jquery', 'mage/loader'], function($) {
    // body 已经添加了 loader 和 loaderAjax 参考"module-theme\view\base\templates\root.phtml"
    var loader = $('body').loader();
    $('#showloader').click(function(){
        loader.loader('show');
        $('#hideloader').css({'position': 'fixed', 'z-index': '10000', 'left': '50%', 'bottom': '50%'})
    })
    $('#hideloader').click(function(){
        loader.loader('hide');
        $(this).css({'position': 'static'})
    })

})
</script>
<pre>ajaxSend 让body多了'ajax-loading' class并设置aria-busy="true", 没有动画</pre>
<div><button id="showajloader">show adjx loader</button><button id="hideajloader">hide ajax loader</button></div>
<script>
require(['jquery', 'mage/loader'], function($) {
    $('#showajloader').click(function(){
        $(document).trigger('ajaxSend');
    })
    $('#hideajloader').click(function(){
        $(document).trigger('ajaxComplete');
    })

})
</script>

<hr>

<h2>Menu: 菜单</h2>
<style>
    #menu-col {display: flex;justify-content: space-between;}
</style>
<ul id="menu-col">
    <li class="ui-menu-item">Adamsville</li>
    <li class="ui-menu-item"><span class="ui-icon ui-icon-print"></span>Addyston</li>
    <li class="ui-menu-item">Delphi
        <ul>
            <li class="ui-state-disabled">Ada</li>
            <li>Saarland</li>
            <li>Salzburg</li>
        </ul>
    </li>
    <li class="ui-menu-item">Saarland</li>
    <li class="ui-menu-item">Salzburg
        <ul>
            <li class="ui-menu-item">Delphi
                <ul>
                    <li class="ui-menu-item">Ada</li>
                    <li class="ui-menu-item">Saarland</li>
                    <li class="ui-menu-item">Salzburg</li>
                </ul>
            </li>
            <li class="ui-menu-item">Delphi
                <ul>
                    <li class="ui-menu-item">Ada</li>
                    <li class="ui-menu-item"> - </li>
                    <li class="ui-menu-item">Saarland</li>
                    <li class="ui-menu-item">Salzburg</li>
                </ul>
            </li>
            <li class="ui-menu-item">Perch</li>
        </ul>
    </li>
</ul>
<script>
require(['jquery', 'mage/menu'], function($){
    $('#menu-col').menu({});
})
</script>



<hr>

<h2>modal</h2>

<div id="modal1">
    <div data-role="content">
        this is popup-modal!
    </div>
</div>
<button id="openmodal1">open popup-modal</button>

<div id="modal2">
    <div data-role="content">
        this is slide-modal!
    </div>
</div>
<button id="openmodal2">open slide-modal</button>

<div id="modal3">
    <div data-role="content">
        this is custom-modal!
    </div>
</div>
<button id="openmodal3">open custom-modal</button>

<script>
require(['jquery', 'Magento_Ui/js/modal/modal'], function($){
    $('#modal1').modal({
        type: 'popup',  //module-ui\view\base\web\templates\modal\modal-popup.html
        modalClass: '',
        responsive: '',
        title: 'title!',
        subtitle: 'subtitle!'
    });
    $('#openmodal1').click(function(){
        $('#modal1').modal('openModal');
    })
    $('#modal2').modal({type: 'slide'});
    $('#openmodal2').click(function(){
        $('#modal2').modal('openModal')
    })

})
</script>

<hr>


<h2>Confirmation: 确认弹窗</h2>
<div><button id="confirm">Confirm</button></div>
<script>
require([
    'Magento_Ui/js/modal/confirm'
], function(confirmation) {
    //https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_confirm.html
    document.getElementById('confirm').addEventListener('click', function(){
        confirmation({
            title: 'Some title',
            content: 'Some content',
            actions: {
                confirm: function(){
                    console.log('confirm')
                },
                cancel: function(){
                    console.log('cancel')
                },
                always: function(){}
            }
        });
    })

});
</script>

<hr>

<h2>Alert: 警告弹窗</h2>
<div><button id="alert">Alert</button></div>
<script>
require([
    'Magento_Ui/js/modal/alert'
], function(alert) {
    document.getElementById('alert').addEventListener('click', function(){
        alert({
            title: 'Some title',
            content: 'Some content',
            actions: {
                always: function(){}
            }
        });
    })
});
</script>


<hr>

<h2>Tabs</h2>
<div id="tabs" data-mage-init='{"tabs": {}}'>
    <div data-role="collapsible">collapsible1</div>
    <div data-role="content">content1</div>
    <div data-role="collapsible">collapsible2</div>
    <div data-role="content">content2</div>
</div>

<br>
<hr>
<hr>
<br>

<h2>Create Jquery widget</h2>
<div id="cus-prog"></div>
<script>
require(['jquery', 'jquery/ui'], function($){
    $.widget( "custom.progressbar", {
        options: {
            value: 0
        },
        _create: function() {
            this.element.addClass( "progressbar" );  
            this.refresh();
        },
        _setOption: function( key, value ) {
            if ( key === "value" ) {
                value = this._constrain( value );
            }
            this._super( key, value );
        },
        _setOptions: function( options ) {
            this._super( options );
            this.refresh();
        },
        // Create a public method.
        refresh: function() {
            var progress = this.options.value + "%";
            this.element.text( progress );
            if ( this.options.value == 100 ) {
                //之后可以在options中添加`complete`选项
                this._trigger( "complete", null, { value: 100 } );
            } 
        },
        // Create a private method.
        _constrain: function( value ) {
            if ( value > 100 ) {
                value = 100;
            }
            if ( value < 0 ) {
                value = 0;
            }
            return value;
        },
        _destroy: function() {
            this.element
                .removeClass("progressbar")
                .text("");
        }
    });
    $('#cus-prog')
        .progressbar({
            complete: function( event, data ) {
                console.log("Callbacks are great!");
            }
        })
        //之后绑定的事件前缀为`progressbar`
        .bind( "progressbarcomplete", function( event, data ) {
            console.log( "Events bubble and support many handlers for extreme flexibility." );
            console.log( "The progress bar value is " + data.value );
        });
    
    //原型扩展
    $.custom.progressbar.prototype.reset = function() {
        this._setOptions({value: 0});
    }

    setTimeout(() => {
        $('#cus-prog').progressbar('option', 'value', 100 );
    }, 2000);
    setTimeout(() => {
        $('#cus-prog').progressbar('reset');
    }, 4000);
})
</script>


<hr>
<h2>Extend Magento Widget</h2>
<pre>
define([
  'jquery',
  'jquery/ui',
  'mage/[widget.name]' // usually widget can be found in /lib/web/mage dir
], function($){
 
  $.widget('[your_namespace].[your_widget_name]', $.mage.[widget.name], { ... });
 
  return $.[your_namespace].[your_widget_name];
});

</pre>


<hr>
<h2>Extend Ui component</h2>
<pre>
define([
  'Magento_Ui/js/grid/filters/filters'
], function(Filters){
 
  return Filters.extend({
 
    defaults: { ... }, // properties with default values
    ... // methods of your component
  });
});
</pre>


<hr>
<h2>Using javascript mixins</h2>
<pre>
//扩展原来的对象
define(['jquery'], function ($) {
  'use strict';
 
  var mixin = {
    domore: function (elem) {
      console.log(elem);
    }
  };
 
  return function (target) {
    return $.extend(target, mixin);
  };
});


//扩展原来的函数
define([
    'jquery',
    'mage/utils/wrapper',
    'Magento_CheckoutAgreements/js/model/agreements-assigner'
], function ($, wrapper, agreementsAssigner) {
    'use strict';

    return function (placeOrderAction) {

        /** Override default place order action and add agreement_ids to request */
        return wrapper.wrap(placeOrderAction, function (originalAction, paymentData, messageContainer) {
            agreementsAssigner(paymentData);

            return originalAction(paymentData, messageContainer);
        });
    };
});
</pre>
<script>
require(['jquery', 'mycss'], function($, mycss) {
    console.log(mycss); //结果显示mycss已添加了`domore`方法
})
</script>