<h2>Frontend Product Repository</h2>

<div id="sub-repo"></div>

<script>
require([
    'jquery', 'Magento_Catalog/js/product/storage/storage-service'
], function($, storage){
    'use strict';
    /*
storage的方法:
createStorage: ƒ (config)
getStorage: ƒ (namespace)
onStorageInit: ƒ (namespace, callback)  //异步
processSubscribers: ƒ (initialized, config)
    */
    var repo = {
        productStorage: null,

        identifiersConfig: {
            namespace: 'product_data_storage'
        },

        productStorageConfig: {
            namespace: 'product_data_storage',
            customerDataProvider: 'product_data_storage',
            className: 'DataStorage'
        },

        initIdsStorage: function(){
            storage.onStorageInit(
                this.identifiersConfig.namespace, //namespace
                this.idsStorageHandler.bind(this) //callback
            );//异步
            return this;
        },

        idsStorageHandler: function(idsStorage, currency, storeId){
            //创建实例
            this.productStorage = storage.createStorage(this.productStorageConfig);
            //订阅storage
            this.productStorage.data.subscribe(this.dataCollectionHandler.bind(this));

            this.productStorage.loadDataFromServer(currency, storeId, idsStorage.get());
        },
        dataCollectionHandler: function(data) {
            console.log(data)
            $('#sub-repo').text(JSON.stringify(data));
        }
    }
    repo.initIdsStorage();
});

</script>